
#
# Configuration file for Travis CI
# http://travis-ci.org/
#

language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8


after_success:
  - cd jsexp ; mvn clean cobertura:cobertura coveralls:report


